apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-random-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/YOUR_GITHUB_REPO/flask-app-openshift
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: flask-random-image:latest
