- name: Deploy Flask App to OpenShift using oc apply
  hosts: localhost
  vars:
    project: flask-random-app
    openshift_api_url: https://api.cluster-fw7hk.fw7hk.sandbox1722.opentlc.com:6443
    openshift_token: sha256~mrUJGIPJy6SgUyDma1C3Xy70vrv1ku1USc_sCfjnocI
    openshift_validate_certs: false

  tasks:
    - name: Login to OpenShift using token
      command: >
        oc login --token={{ openshift_token }}
        --server={{ openshift_api_url }}
        {% if not openshift_validate_certs %}
        --insecure-skip-tls-verify
        {% endif %}

    - name: Create project (ignore if exists)
      command: oc new-project {{ project }}
      register: project_create
      failed_when: false
      changed_when: "'created' in project_create.stdout"

    - name: Apply ImageStream
      command: oc apply -f imagestream.yaml -n {{ project }}

    - name: Apply BuildConfig
      command: oc apply -f buildconfig.yaml -n {{ project }}

    - name: Start build and wait
      command: oc start-build flask-random-build -n {{ project }} --wait

    - name: Apply Deployment
      command: oc apply -f deployment.yaml -n {{ project }}

    - name: Apply Service
      command: oc apply -f service.yaml -n {{ project }}

    - name: Apply Route
      command: oc apply -f route.yaml -n {{ project }}
