---
- name: Deploy Flask App to OpenShift using oc apply
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply BuildConfig
      command: oc apply -f flask-buildconfig.yaml -n flask-random-app

    - name: Apply Deployment
      command: oc apply -f flask-deployment.yaml -n flask-random-app

    - name: Apply Service
      command: oc apply -f flask-service.yaml -n flask-random-app

    - name: Apply Route
      command: oc apply -f flask-route.yaml -n flask-random-app
