apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-random-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/<your-username>/flask-random-app.git
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: flask-random:latest
